### PR TITLE
Adds optional container for scrolling

### PR DESCRIPTION
**Pull request by poacher2k**

### CODE REVIEW

**Comment by fisshy** [comment]
Great! Gonna look through it and make sure all the tests passes. Will get back and hopefully merge it :)

**Comment by poacher2k** [comment]
Awesome!

I ran the tests many, many times, and it seems that at least two of them will randomly pass or fail.

**Comment by fisshy** [comment]
Sweet. Will check everything at lunch today.

**Comment by markusschlebusch** [comment]
Great news! We need this functionality to be able to scroll within a modal window.

**Comment by poacher2k** [comment]
@fisshy: It seems that those two tests consistently fail first by missing 16px, that I think has a connection with this code that I copied from the existing code from `scroller.js`:
```
var bodyRect = document.body.getBoundingClientRect();
var scrollOffset = coordinates.top - bodyRect.top;
```

When I remove `- bodyRect.top` all tests still pass and we get one step further.

Next stop is the the missing 'active' class though, which seem to randomly switch between failing on "is active when clicked" and completing "is active when clicked to last (5) element", and vice versa.

Removing `- bodyRect.top` seems to improve things, so if it's fine with you I'll remove this and push the changes.

**Comment by fisshy** [comment]
I have now merged your PR! I fixed few issues ( absolute was always set to true ) and I also merged it with property warnings and solved a test for that as well.

**Comment by poacher2k** [comment]
Hooray! :smile:

**Pull request merged**
