### PR TITLE
Horizontal scroll support

### PR DESCRIPTION
**Pull request by yoiang**

### CODE REVIEW

**Comment by fisshy** [comment]
Thanks for the PR, probably useful for many.

Missing tests in the PR.

**Comment by yoiang** [comment]
Ah good call, my bad! I'll add them now.

Are you currently running with all tests completing? Even in the **react-scroll** `master` I'm getting the following three tests failing:

>  Events
    ✖ calls "end" event on scrollTo
      Firefox 57.0.0 (Mac OS X 10.15.0)
    Error: Expected 2259 to equal 100 (webpack:///~/expect/lib/assert.js:29:0 <- tests.webpack.js:10760)
>
>  Page
    ✖ is active when clicked
      Firefox 57.0.0 (Mac OS X 10.15.0)
    Error: Expected 1217 to equal 2259 (webpack:///~/expect/lib/assert.js:29:0 <- tests.webpack.js:10760)
>
>  ✖ is active when clicked to last (5) element
      Firefox 57.0.0 (Mac OS X 10.15.0)
    Error: Expected 100 to equal 5427 (webpack:///~/expect/lib/assert.js:29:0 <- tests.webpack.js:10760)

**Comment by yoiang** [comment]
Nix that, it seems like refreshing the open Karma connected browsers results in those tests passing!

**Comment by dav92lee** [comment]
@yoiang thank you so much!!! i need this desperately for my project.

**Comment by dav92lee** [comment]
@fisshy could we possibly get this merged and shipped ?

**Comment by fisshy** [comment]
@dav92lee Yes, most likely, just recieved the changes I've been waiting for.

Tests are important :)

**Comment by fisshy** [comment]
@yoiang Was going to merge this, but the new tests are not passing for me.

**Comment by yoiang** [comment]
@fisshy all are failing or two as mentioned in the commit? I still need to set aside time to sit down and see what's up with those two!

**Comment by softage0** [comment]
Any update on this? I'm so waiting for this :)

**Comment by yoiang** [comment]
@fisshy @dav92lee @softage0 sorry, trying to make time! help taking this PR over the finish line is of course welcome ;)

**Comment by dav92lee** [comment]
@yoiang swamped myself -- promise to give it a try next weekend when I have some time.  Thanks for your work!

**Comment by softage0** [comment]
@yoiang I just sent PR to fix test cases and add several missing features:
https://github.com/Adorkable-forkable/react-scroll/pull/1

Please review this :)

**Comment by yoiang** [comment]
Merge in @softage0 great work! I was getting it to pass sometimes, fail sometimes locally, would anyone have insight into that or is the passing enough?

**Comment by edwinlimlx** [comment]
Nice work guys! any chance this will be release soon?

**Comment by fisshy** [comment]
I have now released it as v1.8.0 :)

**Comment by LeoAmeneiros** [comment]
Thanks for the realease! can you add how to use this new feature it in the docs?

**Pull request merged**
