### PR TITLE
fixing scrollOffset

### PR DESCRIPTION
**Pull request by xodder**
In certain instances where an Element is not a direct descendant of the containerElement, it's offsetTop would be with respect to its parent not the containerElement. A use-case is as follows: 

```html
<div id="scrollable"> <!-- a scrollable entity-->
    <div>...</div><!--a very long entity-->
    <div id="container-1"> <!--not a scrollable entity-->
        <Element name="element-1">...</Element>
        <Element name="element-2">...</Element>
    </div>
    <div id="container-2"> <!--not a scrollable entity-->
        <Element name="element-3">...</Element>
        <Element name="element-4">...</Element>
    </div>
</div>
```

Invoking
```javascript
    scroller.scrollTo("element-x", {
       ...,
       containerId: "scrollable"
    });
```
would probably scroll back to the top (as was in my case) since element-x's offsetTop would be with respect to container-y (it's parent) and not "#scrollable". Setting containerId (in scrollTo) to the corresponding container of element-x wasn't working either, since what is being updated inside animateScroll.js is containerElement.scrollTop and since the corresponding containerElement isn't a scrollable entity, so no scrolling occurred. 

Accumulating the offsetTop of the targetElement and that of its offsetParent until either the current offsetParent is the same as the containerElement ("#scrollable") or document would give the actual offsetTop of the Element. 

Found something similar here: 6c02a597e20a32310c5bdd38a6b7e32695950e40 #403, seems it was removed

### CODE REVIEW

**Comment by fisshy** [comment]
Thanks for the PR, I will look into it later today :)

**Comment by fisshy** [comment]
I've now looked into it, tests passes.

But however, we are lacking tests for containers.

And scrolling within a container does not work anymore.

`TypeError: Cannot read property 'offsetTop' of null`

Run `npm start` and go to
`http://localhost:8080/container/index.html
`

Also testing http://localhost:8080/basic/index.html and clicking `Scroll to element within container` does not work either, it scrolls to the container, but it does not scroll within the container. 

This code does not work

```
 scroller.scrollTo("scroll-container-second-element", {
        duration: 800,
        delay: 0,
        smooth: "easeInOutQuart",
        containerId: "scroll-container",
        offset: 50
      })
```

**Comment by xodder** [comment]
It turned out that my conception of what an offsetParent is, was completely wrong. Already made the necessary changes and also added some comment to help with the understanding of the thought behind the given solution.

**Comment by fisshy** [comment]
Great, will check it out later today :)

**Comment by xodder** [comment]
@fisshy any updates on testing the snippet on your part? I feel it could be a fix to most of the 'not working' issues. 'cos it's been working for me ever since.

You can just go through the commented thought-process and come up with a more suitable solution I think.

**Comment by fisshy** [comment]
@xodder no sorry, been on vacation, will check it out

**Comment by fisshy** [comment]
Seems to work good, thanks for the fix, sorry for the late merge

**Comment by fisshy** [comment]
I've now published it as v.1.8.3

**Pull request merged**
