### PR TITLE
Helpers.js now takes the position of the scroll container into accoun…

### PR DESCRIPTION
**Pull request by erinmeyers88**
…t, instead of defaulting to the top of the browser window.

This allows you to nest a react-scroll area.

### CODE REVIEW

**Comment by fisshy** [comment]
Great, I will check it out tomorrow :)

**Comment by Rfaering** [comment]
I would be very interested in this feature for our application

**Comment by thomsta** [comment]
I'm also very interested in this feature for our application :-)

**Comment by fisshy** [comment]
Merged. Just made a small fix to .getBoundingClientRect because it doesn't exists on document.

**Pull request merged**
