### PR TITLE
hotfix/set-container - fixed method setContainer in animate-scroll

### PR DESCRIPTION
**Pull request by cubooks**
Hello. Sorry for my English.

Use your unit to scroll to the 
`<div id="container"><Element name="element"> content </Element></div>`
and 
`Scroll.scroller.scrollTo('element', {containerId: 'container'});`

There is a problem if we go for the first time, everything works fine, but if the walk on the site, and again go to the page, nothing happens. I found out it's because of what **__containerElement** has been announced, and the second time he has not appropriated. Accordingly, scroll to the item did not work.

See my solution to the problem, and accomplish your goal, what you think about it.

Thank you.

### CODE REVIEW

**Comment by harinair** [comment]
Oh My God! I am so sad I did not read this before. I spent nearly half a day debugging this.
I opened issue #159. Can someone merge this PR and create a new build?

**Comment by fisshy** [comment]
I've merged the fix, but havn't published it yet. @harinair

**Comment by harinair** [comment]
@fisshy TY! Let me know when you are ready to publish a patch.

**Comment by fisshy** [comment]
@harinair This is now published, get the latest version :)

**Pull request merged**
