### PR TITLE
Hash History save issue triggering weird back button issues

### PR DESCRIPTION
**Pull request by IPradyumnaDebnath**
Hash is always pushed to history and saved , Added a option for user to opt for the same.

### CODE REVIEW

**Comment by fisshy** [comment]
Thanks for the PR! 

Could you provide a test-case testing the history?

**Comment by christophercolumbusdog** [comment]
Any update on this change? I'd really love to use the library, but the fact that it pushes a new history entry every time the hash is updated is a deal-breaker. 😢

**Comment by IPradyumnaDebnath** [comment]
@christophercolumbusdog Only if this there is a plan to merge this PR this issue would be fixed in this package, else you can use this file code as util method and manupulat history as required. Don't use hashSpy use onSetActive method to update your hash along with this util method to update hash on link active. Hope this helps

**Comment by fisshy** [comment]
Merged it, sorry for the delay

**Comment by IPradyumnaDebnath** [comment]
@fisshy If you want you can update readme and npm description as well with this new property

**Pull request merged**
