### PR TITLE
Scrollable div

### PR DESCRIPTION
**Pull request by JaeHunRo**
Works without having to pass in parent id as a prop (loops through the parent of the Element dom to find the first parent that is scrollable and selects that parent).
To run tests/ see examples 
```
npm run-script examples
```
and navigate to url 
The app.js in examples is edited to have the Elements inside of a scrollable div (the div scrolls rather than the window).

### CODE REVIEW

**Comment by fisshy** [comment]
going to look through this in the closest days - many changes so I've to put some time into it :)

**Comment by JaeHunRo** [comment]
Awesome thanks so much!

**Comment by JaeHunRo** [comment]
Hey did you check out the updates/ do you have any suggestions for improvement?

**Comment by JaeHunRo** [comment]
bump?

**Comment by fisshy** [comment]
yes sorry - im going to merge it just need some time to go through it - been on vacation but I'm back as normal tomorrow so then I will get some time off :)

**Comment by JaeHunRo** [comment]
Ok awesome! If you recommend any changes or have any questions feel free to say so! I also saw that another person forked from my repo and edited/cleaned up the code so maybe you could take a look at that?

**Pull request closed without merging**
