### PR TITLE
getDOMNode deprecated

### PR DESCRIPTION
**Pull request by JaeHunRo**
also not sure if build needs to be in repo

### CODE REVIEW

**Comment by fisshy** [comment]
Works and verified. Thanks for the PR!

**Comment by JaeHunRo** [comment]
No problem I'm glad you enjoyed my work!
I can edit the readme so it's more clean haha

**Comment by fisshy** [comment]
Was working somewhat unstable - had to reset the commits. 
Scrolling always restarted from position 0 even if you went from Link 4 to Link 5 and there was no scroll-spy working. And It should be optional if you want to use the div as a parent.

**Comment by JaeHunRo** [comment]
ah I see. I'll work on that

**Pull request merged**
