### PR TITLE
Possible Resolution to Issue 55

### PR DESCRIPTION
**Pull request by HeyWrecker**
[Issue 55](https://github.com/fisshy/react-scroll/issues/55)

Somewhat related StackOverflow thread for reference:

[http://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome](http://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome)

### CODE REVIEW

**Comment by fisshy** [comment]
will check it out tomorrow and then possibly merge it :)

**Comment by HeyWrecker** [comment]
Thanks!

**Comment by kifahhk** [comment]
@HeyWrecker thanks for the solution

@fisshy 
It would be great, if you merge and publish it.

I think this was my problem in th first place and not the setTimeout.
#54

**Comment by fisshy** [comment]
Merged but not published yet.

**Comment by HeyWrecker** [comment]
I saw the comment that it was published in 1.0.3 and noticed that the code page says "published v 1.0.3". However, I took a peek inside the animate-scroll.js in the [npm directory ](https://github.com/fisshy/react-scroll/blob/master/build/npm/lib/mixins/animate-scroll.js) and don't see the merge reflected.

**Comment by fisshy** [comment]
hmm.... I will take a look when I get back home.

**Comment by HeyWrecker** [comment]
Any word on this? I've checked the source and it still hasn't been updated to reflect the update from `requestAnimationFrame(animateTopScroll);` to `requestAnimationFrame.call(window, animateTopScroll)`

**Comment by fisshy** [comment]
I'm sorry. I will do it tonight :)

**Comment by fisshy** [comment]
https://github.com/fisshy/react-scroll/blob/master/build/npm/lib/mixins/animate-scroll.js I've fixed it now :)

**Comment by HeyWrecker** [comment]
Awesome, thanks! :smiley:

**Pull request merged**
