### PR TITLE
introduce delay property

### PR DESCRIPTION
**Pull request by piscis**
In order to work with transition effects I had to introduce a delay property. My use case is this:

  1. User clicks on react scroll link
  2. react scroll element receives new height
  3. React scroll calculates offset and scrolls to the resized container element

### CODE REVIEW

**Comment by fisshy** [comment]
Thanks for the PR, will look at it tonight :)

**Comment by piscis** [comment]
Thx

**Comment by fisshy** [comment]
By any chance you change so the setTimeout is called only if the property is provided?

**Comment by piscis** [comment]
@fisshy sure how about so cb0f858

**Comment by fisshy** [comment]
looks good, will test and merge it tomorrow

**Comment by snakeyak** [comment]
This would be really useful, can you please merge it? Thank you

**Comment by fisshy** [comment]
Kinda missed this PR, sorry about that. Can you write a one or two tests for this case? And maybe merge with the new code, kinda changed a lot now.

**Comment by fisshy** [comment]
Merged it anyway, was no big changes. Updated the read me and examples as well.

**Pull request merged**
