### PR TITLE
Gets container when calling scrollToBottom and scrollMore

### PR DESCRIPTION
**Pull request by poacher2k**
In reference to [this comment](https://github.com/fisshy/react-scroll/pull/33#issuecomment-230987378) by @cersfeld

### CODE REVIEW

**Comment by fisshy** [comment]
Great. Will merge and publish after lunch today :+1:

**Comment by poacher2k** [comment]
Awesome! Thanks @fisshy!

**Comment by fisshy** [comment]
No problem, published it in v1.0.21. 

And btw, be a bit careful when you set something to null (https://github.com/poacher2k/react-scroll/blob/d94dfab973b911db005cc49792a94f96093ef9b5/modules/mixins/animate-scroll.js#L130) but then you compare it to undefined(https://github.com/poacher2k/react-scroll/blob/d94dfab973b911db005cc49792a94f96093ef9b5/modules/mixins/animate-scroll.js#L137).

I solved it in my latest commit, usually if(!containerElement) works.

**Comment by poacher2k** [comment]
Thanks! Didn't notice that! I'll keep it in mind.

**Pull request merged**
