### PR TITLE
Don't pass all props / new 15.2 warning fix

### LINKED ISSUE #94: Unknown props spy, smooth, duration on <a> tag
Hi, I get a warning when I update my react version to 15.2.0.
```
Warning: Unknown props `spy`, `smooth`, `duration` on <a> tag. Remove these props from the element
```

I use "Link", "Element" to scroll my screen. 

Thank you.

### PR DESCRIPTION
**Pull request by nbrady-techempower**
fixes #94 unused props warning
https://fb.me/react-unknown-prop

### CODE REVIEW

**Comment by codetony25** [comment]
Yes!!! +1

**Comment by fisshy** [comment]
Thanks! Merged :)

**Comment by jeroenverfallie** [comment]
@fisshy Looks like this is not published after all (no changes in lib) 1.0.19.

**Comment by fisshy** [comment]
you are so right @jeroenverfallie. nice catch, I actually ran the wrong command when publishing so I didn't get the correct build. Thanks!

**Comment by fisshy** [comment]
It's now in v1.0.20

**Pull request merged**
