### PR TITLE
Multiple scrolls

### PR DESCRIPTION
**Pull request by yaruson**
Hello,

I had to scroll through several containers, but because of the shared global variables like `__containerElement`  it didn't work. In this PR, I suggest to keep all private fields in the `options.data` object as a possible solution of the problem.

I'm not sure about `cancelEvents` thing and would be happy to get feedback at this point.

### CODE REVIEW

**Comment by fisshy** [comment]
Thanks for the PR, let me check it out later today.

**Comment by alexdemartos** [comment]
Tested and working like a charm. Thank you both.

**Comment by doochik** [comment]
@fisshy Can you merge it, please?

**Comment by fisshy** [comment]
Will check it out today and then hopefully merge it if all tests pass :) @doochik

**Comment by fisshy** [comment]
Published in v1.7.0.

**Pull request merged**
