### PR TITLE
build published package with babel

### PR DESCRIPTION
**Pull request by joeduncan**
This fixes https://github.com/fisshy/react-scroll/issues/202

@fisshy I don't know exactly how you publish this package, but on the long run it might be better taking `build/**` out of the repo and just simply running a `prepublish` script that clears and transpiles the files.
https://github.com/airbnb/enzyme/blob/master/package.json might be a good example

### CODE REVIEW

**Comment by fisshy** [comment]
I just copy to build and publish the build folder, tranforming it with babel seems like a good option.

**Comment by sugarshin** [comment]
Hi,

Why include build assets in this repository ? I don't think that it is necessary.

**Comment by fisshy** [comment]
@sugarshin You are correct, no need to include the build. I've now removed it from the repo. Merged and published using babel.

**Comment by sugarshin** [comment]
@fisshy ok thank you!

**Pull request merged**
