### PR TITLE
onSetInactive callback function added to Link

### PR DESCRIPTION
**Pull request by aujeah**
I missed this callback function because I need to change the Link's inline style inside the component.

### CODE REVIEW

**Comment by fisshy** [comment]
Good PR, I think this might be usefull for others aswell.

**Comment by fisshy** [comment]
Can you update the README with few lines of documentation for this?

**Comment by aujeah** [comment]
Ofcourse, if I will have a little free time today.

**Comment by aujeah** [comment]
I have updated the readme, now I can see this commit too in this pull request.

**Comment by fisshy** [comment]
Merged, will publish later tonight.

**Pull request merged**
